# Generated by Django 3.0.6 on 2020-05-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwatweet', '0004_auto_20200510_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('username', 'post')},
        ),
    ]
